        <footer class="footer text-center">
            <div class="container">
                <div class="row">
                    <!-- Footer Social Icons-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <a class="btn btn-outline-light btn-social mx-1" href="https://github.com/mpound/pdrtpy">
                        <i class="fab fa-fw fa-github" title="Visit us on Github"></i></a>

                        <a class="btn btn-outline-light btn-social mx-1" href="https://pdrtpy.readthedocs.io" title="Visit us on ReadTheDocs">
                        <i class="fa fa-fw fa-book"></i></a>
                        <a class="btn btn-outline-light btn-social mx-1" href="https://www.umd.edu/web-accessibility" title="UMD Web Accessibility">
                        <i class="fa fa-fw fa-universal-access"></i></a>
                    </div>
                    <!-- Footer Location-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <p class="pre-wrap lead mb-0">Astronomy Department<br>University of Maryland<br>College Park, MD 20740</p>
                    </div>
                    <!-- Footer LOGOS-->
                    <div class="col-lg-1 mb-5 mb-lg-0">
                        <a class="btn btn-outline-light btn-social mx-1" href="https://www.umd.edu" title="University of Maryland">
                        <img class="p-3" src="/images/New_UMD_Globe_small.png" width="100px" alt="UMD logo">
                        </a>
                    </div>
                    <div class="col-lg-1 mb-5 mb-lg-0">
                     <a class="btn btn-outline-light btn-social mx-1 p-3" href="http://www.nasa.gov" title="NASA">
                     <img class="p-3" src="/images/nasa-logo-web-rgb.png" width="120px" alt="NASA logo">
                     </a>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Copyright Section-->
        <div class="copyright py-4 text-center text-white">
            <div class="container"><small class="pre-wrap">Copyright &copy; 2Marx Productions 2020 </small></div>
        </div>

<!-- Javascript includes -->
        <div id="scripting">
            <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes)-->
            <div class="scroll-to-top d-lg-none position-fixed"><a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top"><i class="fa fa-chevron-up"></i></a></div>
            <!-- Bootstrap core JS-->
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
            <!-- Third party plugin JS-->
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
            <!-- LaTeX math in HTML -->
            <script async="async" type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS-MML_HTMLorMML"></script>
            <!-- Core theme JS from https://startbootstrap.com/themes/freelancer/-->
            <script src="freelancer/js/scripts.js"></script>
        </div>

