<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Tools to analyze observations of photodissociation regions">
    <meta name="author" content="Marc W. Pound">
    <title>PhotoDissociation Region Toolbox</title>
    <!-- Font Awesome icons (free version)-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>
    <!-- Font Awesome accessibility options -->
    <script src="https://use.fontawesome.com/824d9b17ca.js"></script>
    <!-- Core theme CSS (includes Bootstrap)-->
    <!-- from https://startbootstrap.com/themes/freelancer/-->
    <link href="/freelancer/css/styles.css" rel="stylesheet">
    <!-- Fonts CSS-->
    <!-- from https://startbootstrap.com/themes/freelancer/-->
    <link rel="stylesheet" href="/freelancer/css/heading.css">
    <link rel="stylesheet" href="/freelancer/css/body.css">

    <!-- PDRT specific CSS -->
    <link href="/css/pdrt.css" rel="stylesheet">
</head>
